export const ROLES = {
  USER: 'user',
  ADMIN: 'admin',
} as const;

export const CAMPAIGN_TYPES = {
  SUBSCRIBER: 'SUBSCRIBER',
  LIKE: 'LIKE',
} as const;

export const CAMPAIGN_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_REVIEW: 'PENDING_REVIEW',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const PARTICIPATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  REVIEW: 'REVIEW',
  EXPIRED: 'EXPIRED',
} as const;

export const TRANSACTION_TYPES = {
  PURCHASE: 'PURCHASE',
  CAMPAIGN_RESERVE: 'CAMPAIGN_RESERVE',
  ACTION_REWARD: 'ACTION_REWARD',
  CAMPAIGN_REFUND: 'CAMPAIGN_REFUND',
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT',
  REFERRAL_REWARD: 'REFERRAL_REWARD',
  NEW_USER_BONUS: 'NEW_USER_BONUS',
} as const;

export const PURCHASE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const NOTIFICATION_TYPES = {
  CAMPAIGN_APPROVED: 'CAMPAIGN_APPROVED',
  CAMPAIGN_REJECTED: 'CAMPAIGN_REJECTED',
  COINS_RECEIVED: 'COINS_RECEIVED',
  COINS_PURCHASE_APPROVED: 'COINS_PURCHASE_APPROVED',
  COINS_PURCHASE_REJECTED: 'COINS_PURCHASE_REJECTED',
  CAMPAIGN_COMPLETED: 'CAMPAIGN_COMPLETED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  ACCOUNT_WARNING: 'ACCOUNT_WARNING',
} as const;

export const AUDIT_ACTIONS = {
  APPROVE_COIN_REQUEST: 'APPROVE_COIN_REQUEST',
  REJECT_COIN_REQUEST: 'REJECT_COIN_REQUEST',
  SUSPEND_USER: 'SUSPEND_USER',
  REACTIVATE_USER: 'REACTIVATE_USER',
  ADJUST_COINS: 'ADJUST_COINS',
  PAUSE_CAMPAIGN: 'PAUSE_CAMPAIGN',
  CANCEL_CAMPAIGN: 'CANCEL_CAMPAIGN',
  APPROVE_VERIFICATION: 'APPROVE_VERIFICATION',
  REJECT_VERIFICATION: 'REJECT_VERIFICATION',
  UPDATE_SYSTEM_SETTINGS: 'UPDATE_SYSTEM_SETTINGS',
} as const;

export const RISK_LEVELS = {
  LOW: { min: 0, max: 30, label: 'Normal' },
  MEDIUM: { min: 31, max: 70, label: 'Review' },
  HIGH: { min: 71, max: 100, label: 'High Risk' },
} as const;

export const DEFAULT_COIN_PACKAGES = [
  { id: 'pkg_100', coins: 100, price: 0.99, label: 'Starter Pack', popular: false },
  { id: 'pkg_500', coins: 500, price: 4.49, label: 'Creator Pack', popular: true },
  { id: 'pkg_1000', coins: 1000, price: 7.99, label: 'Growth Pack', popular: false },
  { id: 'pkg_5000', coins: 5000, price: 34.99, label: 'Studio Pro', popular: false },
];
